# Generated by Django 4.1.6 on 2023-11-22 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_attendance_bg_grp_alter_attendance_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='bg_grp',
            field=models.CharField(default='default', max_length=4),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='contact',
            field=models.CharField(default='default', max_length=13),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='experience',
            field=models.CharField(default='default', max_length=15),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='mail_id',
            field=models.CharField(default='default', max_length=48),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='role',
            field=models.CharField(default='default', max_length=64),
        ),
    ]
