# Generated by Django 4.1.6 on 2023-11-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_remove_attendance_age_remove_attendance_bg_grp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='Age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendance',
            name='bg_grp',
            field=models.CharField(default='default', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='contact',
            field=models.CharField(default='default', max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='experience',
            field=models.CharField(default='default', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='mail_id',
            field=models.CharField(default='default', max_length=48, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='role',
            field=models.CharField(default='default', max_length=64, null=True),
        ),
    ]
