# Generated by Django 4.1.6 on 2023-11-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_employeeleaves'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeleaves',
            name='remark',
            field=models.CharField(default='default', max_length=200, null=True),
        ),
    ]
