# Generated by Django 4.1.6 on 2023-11-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_employeeleaves_remark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventoy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_des', models.CharField(max_length=200, null=True)),
                ('partcode', models.CharField(max_length=30, null=True)),
                ('hsncode', models.BigIntegerField()),
                ('price', models.BigIntegerField()),
                ('qty', models.IntegerField()),
                ('remarks', models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
