# Generated by Django 4.1.6 on 2023-11-29 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_inventoy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inventoy',
            new_name='Inventory',
        ),
    ]
