# Generated by Django 5.0 on 2023-12-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0019_conveyance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conveyance',
            name='Kms',
            field=models.CharField(max_length=10),
        ),
    ]
