# Generated by Django 5.0 on 2023-12-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0020_alter_conveyance_kms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conveyance',
            name='Kms',
            field=models.IntegerField(),
        ),
    ]
