# Generated by Django 5.0 on 2023-12-26 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0021_alter_conveyance_kms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conveyance',
            name='total_Kms',
        ),
    ]
